{{- if .Values.ingressroute.enabled -}}
{{- $serviceName := include "oauth2-proxy.fullname" . -}}
{{- $servicePort := .Values.service.portNumber -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ include "oauth2-proxy.fullname" . }}.{{.Values.domain }}`) && PathPrefix(`/`)
      middlewares:
        - name: {{.Release.Namespace}}-{{ include "oauth2-proxy.fullname" . }}-headers@kubernetescrd
      services:
        - name: {{ template "oauth2-proxy.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: {{ $servicePort }}
  tls: {}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    oauth2-proxy-header: ""
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}-headers
spec:
  headers:
     browserXssFilter: true
     contentTypeNosniff: true
     forceSTSHeader: true
     frameDeny: true
     stsIncludeSubdomains: true
     stsPreload: true
     stsSeconds: 315360000

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    oauth2-proxy-forwardauth: ""
    app: {{ template "oauth2-proxy.name" . }}
{{- include "oauth2-proxy.labels" . | indent 4 }}
  name: {{ template "oauth2-proxy.fullname" . }}-forwardauth
spec:
  forwardAuth:
    address: http://{{ include "oauth2-proxy.fullname" . }}.{{ .Release.Namespace }}.svc/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-Access-Token
      - Authorization
{{- end -}}