# Default values for console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: "console"

domain: ""
subDomain: "console"
timeZone: "UTC"

config:
  hyperAuth:
    address: ""
    realm: "tmax"
    clientID: "hypercloud5"
  mcMode: true
  chatbotEmbed: true
  customProductName: "hypercloud"
  k8sPublicEndpoint: "https://kubernetes.default.svc"
  # Ingress 주소 조회 시 api-gateway 서비스 타입을 확인
  # NodePort 일 경우 대응되는 포트번호를 조회
  # LoadBalancer, NodePort 중 택 1
  svcType: "LoadBalancer"
  logLevel: "debug"
  logType: "pretty"

image:
  repository: "docker.io/tmaxcloudck/hypercloud-console"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "5.2.10.0"
imagePullSecrets: []
#imagePullSecrets:
#  - name: regcred
service:
  type: ClusterIP
  port: 31303
#nodeSelector:
#  node-role.kubernetes.io/master: ""

#tolerations: []
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: Exists

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - traefik
        weight: 100

replicaCount: 1

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

podAnnotations: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

