{{- if .Values.modules.gatewayBootstrap.console.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "jwt-decode-auth" }}
{{ $hyperAuthDomain := include "hyperAuth.domain" . }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 1
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "1m0s"
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: api-gateway-system
  project: {{ .Values.spec.project }}
  source:
    path: charts/jwt-decode-auth
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: jwt-decode-auth
      valueFiles:
        - values.yaml
      parameters:
        - name: timeZone
          value: {{ .Values.global.timeZone | default "UTC" }}
        {{- with .Values.modules.gatewayBootstrap.hyperAuthInfo }}
        - name: hyperAuth.address
          value: {{ .address | default $hyperAuthDomain }}
        - name: hyperAuth.realm
          value: {{ .realm | default "tmax" }}
        {{- end }}
        {{- with .Values.modules.gatewayBootstrap.console }}
        - name: logInfo.logType
          value: {{ .logInfo.logType | default "pretty" }}
        - name: logInfo.logLevel
          value: {{ .logInfo.logLevel | default "debug" }}
        {{- end }}
        {{- if .Values.global.privateRegistry }}
        - name: image.repository
          value: {{ .Values.global.privateRegistry }}/docker.io/tmaxcloudck/jwt-decode
        {{- end }}
        - name: image.tag
          value: {{ .Values.modules.gatewayBootstrap.jwtDecodeAuth.version | default "5.0.0.3" }}
{{- end }}