{{ $isMaster := eq .Values.global.cluster "master" }}
{{ if .Values.modules.gitea.enabled }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "gitea" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: gitea-system
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        - name: global.registry.is_offline
          value: "{{ .Values.global.network.disabled }}"
        - name: global.registry.private_registry
          value: {{ .Values.global.privateRegistry }}
        - name: ingress.hosts.domain
          value: {{ .Values.global.domain }}
        - name: ingress.hosts.subdomain
          value: {{ .Values.modules.gitea.subdomain }}
        - name: gitea.config.server.DOMAIN
          value: {{ printf "%s.%s" .Values.modules.gitea.subdomain .Values.global.domain }}
        - name: gitea.config.server.ROOT_URL
          value: {{ printf "https://%s.%s" .Values.modules.gitea.subdomain .Values.global.domain }}
        - name: gitea.config.server.SSH_DOMAIN
          value: {{ printf "%s.%s" .Values.modules.gitea.subdomain .Values.global.domain }}
        - name: gitea.config.log.LEVEL
          value: {{ .Values.modules.gitea.logLevel }}
        - name: gitea.oauth[0].key
          value: {{ ternary "gitea" (printf "%s-gitea" $prefix) $isMaster }}
        - name: gitea.oauth[0].secret
          value: {{ include "hyperAuth.tmaxClientSecret" . }}
        - name: gitea.oauth[0].autoDiscoverUrl
          value: https://{{ include "hyperAuth.domain" . }}/auth/realms/tmax/.well-known/openid-configuration
    path: manifest/gitea
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}
