{{ if .Values.modules.hyperAuth.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "hyperauth" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: hyperauth
  project: {{ .Values.spec.project }}
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "{{ .Values.global.network.disabled }}"
          - name: private_registry
            value: {{ .Values.global.privateRegistry }}
          - name: hyperauth_svc_type
            value: {{ .Values.modules.hyperAuth.svcType }}
          - name: is_kafka_enabled
            value: "{{ .Values.modules.strimziKafka.enabled }}"
          - name: hypercloud_domain_host
            value: {{ .Values.global.domain }}
          - name: hyperauth_subdomain
            value: {{ include "hyperAuth.subdomain" . }}
          - name: storage_class
            value: {{ .Values.modules.hyperAuth.storageClass }}
          - name: timezone_setting
            value: {{ .Values.global.timeZone }}
    path: manifest/hyperauth
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}