{{ $isMaster := eq .Values.global.cluster "master" }}
{{ if .Values.modules.nexus.enabled }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "nexus" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: nexus
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        - name: global.registry.is_offline
          value: "{{ .Values.global.network.disabled }}"
        - name: global.registry.private_registry
          value: {{ .Values.global.privateRegistry }}
        - name: ingress.hosts.domain
          value: {{ .Values.global.domain }}
        - name: nexus.properties.data.root.level
          value: {{ .Values.modules.nexus.logLevel }}
        - name: global.timezone
          value: {{ .Values.global.timeZone }}
        - name: persistence.enabled
          value: "{{ .Values.modules.nexus.persistence.enabled }}"
        - name: persistence.storageClass
          value: "{{ .Values.modules.nexus.persistence.storageClass }}"
    path: manifest/nexus
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}
