{{- if .Values.modules.redis.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ .Values.spec.destination.label }}
  {{- if eq .Values.spec.destination.label "master" }}
  name: otcontainerkit-redis-operator
  {{- else }}
  name: {{ .Values.spec.destination.clusterInfo }}-otcontainerkit-redis-operator
  {{- end }}
  namespace: argocd
spec:
  destination:
    namespace: redis-operator
    {{- if eq .Values.spec.destination.type "name" }}
    name: {{ .Values.spec.destination.clusterInfo }}
    {{- else if eq .Values.spec.destination.type "server" }}
    server: {{ .Values.spec.destination.clusterInfo }}
    {{- end }}
  project: {{ .Values.spec.project }}
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "{{ .Values.global.network.disabled }}"
          - name: private_registry
            value: {{ .Values.global.privateRegistry }}
    path: manifest/otcontainerkit-redis-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }} 
{{- end }}