{{ if .Values.modules.prometheus.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "prometheus" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: monitoring
  project: {{ .Values.spec.project }}
  source:
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "{{ .Values.global.network.disabled }}"
          - name: private_registry
            value: {{ .Values.global.privateRegistry }}
          - name: configmap_reload_version
            value: {{ .Values.modules.prometheus.versions.cmReload }}
          - name: configmap_reloader_version
            value: {{ .Values.modules.prometheus.versions.cmReloader }}
          - name: prometheus_operator_version
            value: {{ .Values.modules.prometheus.versions.operator }}
          - name: alertmanager_version
            value: {{ .Values.modules.prometheus.versions.alertManager }}
          - name: kube_rbac_proxy_version
            value: {{ .Values.modules.prometheus.versions.kubeRbacProxy }}
          - name: kube_state_metrics_version
            value: {{ .Values.modules.prometheus.versions.kubeStateMetrics }}
          - name: node_exporter_version
            value: {{ .Values.modules.prometheus.versions.nodeExporter }}
          - name: prometheus_adapter_version
            value: {{ .Values.modules.prometheus.versions.adapter }}
          - name: prometheus_pvc
            value: {{ .Values.modules.prometheus.pvcSize }}
          - name: prometheus_version
            value: {{ .Values.modules.prometheus.versions.prometheus }}
          - name: timezone
            value: {{ .Values.global.timeZone }}
    path: manifest/prometheus
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}