# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tags:
  traefik: true

traefik:
  fullnameOverride: "gateway"
  additionalArguments:
    # Only use dev environment
    - "--serverstransport.insecureskipverify=true"
    - "--serverstransport.rootcas=/run/secrets/tmaxcloud/ca.crt, /run/secrets/kubernetes.io/serviceaccount/ca.crt"
    - "--entrypoints.websecure.http.middlewares=cors-header@file"
  image:
    name: traefik
  deployment:
    podLabels:
      app: traefik
    imagePullSecrets:
      - name: regcred
  volumes:
    - name: gateway-config
      mountPath: "/gateway-config"
      type: configMap
    - name: selfsigned-ca
      mountPath: "/run/secrets/tmaxcloud"
      type: secret
  ingressClass:
    enabled: true
    isDefaultClass: true
    fallbackApiVersion: "v1"
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
## When using NodePort service
#    type: NodePort
#  ports:
#    k8s:
#      nodePort: 31643
#    web:
#      nodePort: 31080
#    websecure:
#      nodePort: 31433
#    traefik:
#      nodePort: 31900
  resources: {}
  nodeSelector:
    node-role.kubernetes.io/master: ""
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists

tls:
  acme:
    enabled: false
    email: yjs890403@gmail.com
    dns:
      type: route53
      accessKeyID: AKIA5D7L5Q3I7VQCJETF
      accessKeySecret: 19G1ETeGgjwW6+LDEFDFDVDVDFFDVD
    domains:
      - tmaxcloud.org
    environment: staging
  selfsigned:
    createTLS: true
    useDefaultTLS: true
    commonName: tmaxcloud.local
    domains:
      - tmaxcloud.local