apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    
    ingester:
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_retain_period: 30s
      max_transfer_retries: 0
      lifecycler:
        address: 0.0.0.0
        ring:
          replication_factor: 1
          kvstore:
            store: inmemory
        final_sleep: 0s
    
    querier:
      max_concurrent: 2048
    
    query_scheduler:
      max_outstanding_requests_per_tenant: 2048
    
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 72h
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
    
    schema_config:
      configs:
      - from: 2022-07-10
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
     # grpc_server_max_recv_msg_size:
     # grpc_server_max_send_msg_size:
     # log_level:
    
    #grpc_client_config:
    #  max_recv_msg_size:
    #  max_send_msg_size:
    
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    
    chunk_store_config:
      max_look_back_period: 72h
    
    table_manager:
      retention_deletes_enabled: true
      retention_period: 72h
    
    compactor:
      working_directory: /loki/compactor
      shared_store: filesystem
