apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/prometheus
    repoURL: 'https://github.com/tmax-cloud/argocd-installer'
    targetRevision: main
    directory:
      jsonnet:
        tlas:
          - name: is_offline
            value: "false"
          - name: private_registry
            value: 172.22.6.2:5000
          - name: coreos_image_repo
            value: quay.io/coreos
          - name: prometheus_image_repo
            value: quay.io/prometheus
          - name: prometheus_operator_image_repo
            value: quay.io/prometheus-operator
          - name: kube_state_metrics_image_repo
            value: k8s.gcr.io/kube-state-metrics
          - name: brancz_image_repo
            value: quay.io/brancz
          - name: prometheus_adapter_image_repo
            value: k8s.gcr.io/prometheus-adapter
          - name: configmap_reload_version
            value: v0.0.1
          - name: configmap_reloader_version
            value: v0.51.2
          - name: prometheus_operator_version
            value: v0.51.2
          - name: alertmanager_version
            value: v0.23.0
          - name: kube_rbac_proxy_version
            value: v0.11.0
          - name: kube_state_metrics_version
            value: v2.2.3
          - name: node_exporter_version
            value: v1.2.2
          - name: prometheus_adapter_version
            value: v0.9.1
          - name: prometheus_pvc
            value: 10Gi
          - name: prometheus_version
            value: v2.30.3
  project: default
