spec:
  source:
    # description
    # https연결만 사용 가능합니다.
    # gitlab의 경우, url 마지막에 '.git' suffix를 붙여주셔야 합니다
    repoURL: https://github.com/tmax-cloud/argocd-installer
    # description: target branch or release name
    targetRevision: HEAD
    
global:
  network:
    # 폐쇄망일경우 true
    disabled: false
  domain: testdomain.com
  keycloak:
    domain: testauth.testdomain.com
    # Do not change value of tmaxClientSecret!
    tmaxClientSecret: tmax_client_secret
